apiVersion: v1
kind: Service
metadata:
  name: cupcake-frontend-service
  labels:
    app: cupcake-frontend
spec:
  type: LoadBalancer  # Change to NodePort if you're not using a cloud provider
  ports:
    - port: 80
      targetPort: 3000  # Internal port of the container
  selector:
    app: cupcake-frontend